### ISSUE TITLE
reverse queue, peek via postion?

### ISSUE THREAD

**Issue by sirvon** [iron-io/iron_mq_python#34]
Does the ability to peek/get message off queue by its position exists?

for instance, to get the 3rd to last message.

or

Reverse the queue and have the last message turn into the first?

I know I probably can peek, and then start to parse my way to a solution.

But is there an in built solution that would eliminate a few lines of code and some time off the design of a solution.

thanks!

**Comment by edsrzf** [comment]
Neither reversing the queue or getting a message by position are directly supported because they're not really in the spirit of a queue.

However, you could try calling `peek` with `max` == 3, for example, to get the third message from the queue. Beware that `peek` is not guaranteed to return the number of messages you ask for even if there are enough messages on the queue. It will, however, return at least one (assuming there's at least one on the queue).

I'm going to go ahead and close this issue. It's best to email support@iron.io if you have further questions.
